spring:
  security:
    user:
      password: 1234
      name: user
  datasource:
    url: jdbc:mariadb://${DB_HOSTNAME}:3306/carvery
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        jdbc.time_zone: Asia/Seoul # 한국 시간대 설정
        format_sql: true # SQL 포맷을 쉽게 보기 위해 true
        show_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: none # validate, create 등 필요에 따라 설정
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false


# Google API 설정 (무료 한도)
google:
  api:
    url: https://maps.googleapis.com/maps/api/place/nearbysearch/json
    key: ${GOOGLE_API_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    url: /api-docs
    config-url: /api-docs/swagger-config
    urls:
      - url: /api-docs
        name: API Documentation
  api-docs:
    path: /api-docs
    resolve-schema-properties: true
  cache:
    disabled: true

server:
  port: 8080
  address: 0.0.0.0